// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/company": {
    params: {};
  };
  "/portfolio": {
    params: {};
  };
  "/contacts": {
    params: {};
  };
  "/vacancies": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/service/:slug": {
    params: {
      "slug": string;
    };
  };
  "/drone-defense": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/company" | "/portfolio" | "/contacts" | "/vacancies" | "/services" | "/service/:slug" | "/drone-defense" | "/privacy" | "/terms" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/company.tsx": {
    id: "routes/company";
    page: "/company";
  };
  "routes/portfolio.tsx": {
    id: "routes/portfolio";
    page: "/portfolio";
  };
  "routes/contacts.tsx": {
    id: "routes/contacts";
    page: "/contacts";
  };
  "routes/vacancies.tsx": {
    id: "routes/vacancies";
    page: "/vacancies";
  };
  "routes/services.tsx": {
    id: "routes/services";
    page: "/services";
  };
  "routes/service-detail.tsx": {
    id: "routes/service-detail";
    page: "/service/:slug";
  };
  "routes/drone-defense.tsx": {
    id: "routes/drone-defense";
    page: "/drone-defense";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "$.tsx": {
    id: "$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/company": typeof import("./app/routes/company.tsx");
  "routes/portfolio": typeof import("./app/routes/portfolio.tsx");
  "routes/contacts": typeof import("./app/routes/contacts.tsx");
  "routes/vacancies": typeof import("./app/routes/vacancies.tsx");
  "routes/services": typeof import("./app/routes/services.tsx");
  "routes/service-detail": typeof import("./app/routes/service-detail.tsx");
  "routes/drone-defense": typeof import("./app/routes/drone-defense.tsx");
  "routes/privacy": typeof import("./app/routes/privacy.tsx");
  "routes/terms": typeof import("./app/routes/terms.tsx");
  "$": typeof import("./app/$.tsx");
};